//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int ConsultationID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string AdditionalInformation { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public System.TimeSpan ScheduleTime { get; set; }
        public Nullable<int> StatusGroupID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string LastModifiedByUserID { get; set; }
        public Nullable<int> AssignedToUserID { get; set; }
        public Nullable<int> ConsultantUserID { get; set; }
        public Nullable<System.DateTime> ActualConsultationDate { get; set; }
        public string ConsultantComment { get; set; }
    }
}
