//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ContactUsID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> CreatedByWhoID { get; set; }
        public Nullable<int> AssignedToWhoID { get; set; }
        public Nullable<System.DateTime> AssignedOnDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Notes { get; set; }
        public string CommentOfAssignee { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> LastModifiedByWhoID { get; set; }
    }
}
