//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.States = new HashSet<State>();
        }
    
        public int CountryID { get; set; }
        public string CountryCode { get; set; }
        public string CountryPhoneCode { get; set; }
        public string CountryName { get; set; }
        public string CountryFlag { get; set; }
        public string CountryCapital { get; set; }
        public string CountryCurrency { get; set; }
        public string CountryNationality { get; set; }
        public string CountryPerson { get; set; }
        public string Language { get; set; }
        public Nullable<int> CountryPopulation { get; set; }
        public string IpAddress { get; set; }
        public string Workstation { get; set; }
        public Nullable<int> ApprovedByUserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> ModuleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States { get; set; }
    }
}
