//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment
    {
        public int EnvironmentID { get; set; }
        public string EnvironmentName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    }
}
