//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionLogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int LevelID { get; set; }
        public int LevelTypeID { get; set; }
        public string Message { get; set; }
        public string ExceptionType { get; set; }
        public string StackTrace { get; set; }
        public string Source { get; set; }
        public string MethodName { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string RequestPath { get; set; }
        public string HttpMethod { get; set; }
        public string AdditionalData { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public string CorrelationID { get; set; }
        public string ClientIp { get; set; }
        public string UserAgent { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
    }
}
