//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OmnipurseDBEntities : DbContext
    {
        public OmnipurseDBEntities()
            : base("name=OmnipurseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<TableChangeAudit> TableChangeAudits { get; set; }
        public virtual DbSet<PersonPersonType> PersonPersonTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LevelType> LevelTypes { get; set; }
    }
}
