//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Username { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public string PhoneMobileCountryCode { get; set; }
        public string PhoneMobile { get; set; }
        public string PhoneHomeCountryCode { get; set; }
        public string PhoneHome { get; set; }
        public string EmailAddress { get; set; }
        public string EmailAddress2 { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public Nullable<int> PersonTypeID { get; set; }
        public string PhotoURL { get; set; }
        public byte[] PhotoData { get; set; }
        public string Notes { get; set; }
        public string FolderName { get; set; }
        public string ReferralCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ReferredByPersonID { get; set; }
        public string ReferredByReferralCode { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<int> ModuleID { get; set; }
    }
}
