//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int SystemSettingID { get; set; }
        public string SETTING_NAME { get; set; }
        public string SETTING_VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DATA_TYPE { get; set; }
        public Nullable<bool> IS_VISIBLE { get; set; }
        public Nullable<int> CREATED_BY_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_ON_DATE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string WHAT_WAS_DONE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_ON_DATE { get; set; }
        public Nullable<int> LAST_MODIFIED_BY_USER_ID { get; set; }
    }
}
