//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableChangeAudit
    {
        public int TableChangeAuditID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> TablePrimaryKeyID { get; set; }
        public string ActionTakenThread { get; set; }
        public string ChangedByUserIDThread { get; set; }
        public string ChangeThread { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public string ChangedColumns { get; set; }
        public string UserIp { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
