//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<bool> IsPasswordUserDefined { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserRole { get; set; }
        public Nullable<System.DateTime> LastLoginOnDate { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public string ResetToken { get; set; }
        public Nullable<System.DateTime> ResetTokenExpires { get; set; }
        public string RememberToken { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<System.DateTime> LockedUntil { get; set; }
    }
}
